[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "eslint-lang-server" ]
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "eslint-lang-server" ]
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "eslint-lang-server" ]
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "eslint-lang-server" ]
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "json"
formatter = { command = "prettier" }
auto-format = true

[language-server.eslint-lang-server]
command = "eslint-lang-server"
